In [1]:
print([1,2,3]+[4,5,6])

[1, 2, 3, 4, 5, 6]


In [2]:
print([1,2,3]*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [10]:
import numpy as np
#Creating array from list
a1=np.array([1,2,3])       # 1 dimensional
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])  # 2 dimensional
print(a1,"\n",a2)
print(a1.shape, a2.shape)
#print([1,2,3])
#Elements of array is seperated by space and elements of list seperated by comma

[1 2 3] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3,) (3, 3)


In [9]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]]])          #3 dimensional
print(a3, a3.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] (2, 3, 3)


In [11]:
print(a1*3)

[3 6 9]


In [27]:
# Different methods to generate array
# One dimensional method
a4=np.arange(50)
print(a4)
a5=np.linspace(1,10)
print(a5.shape)
a6=np.ones(4)
print(a6)
a7=np.zeros(5)
print(a7)
a8=np.random.randint(1,100,7)
print(a8)
a9=np.random.rand(5)    #uniform distribution  
print(a9)
a10=np.random.randn(6)  #normal Distribution
print(a10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
(50,)
[1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[23 38 73 32 92 85 31]
[0.03302869 0.85851472 0.03819489 0.1469299  0.97686839]
[ 0.33779849 -0.43288564  0.03030969 -0.27814745  0.58404801  0.70474856]


In [30]:
a1_2=np.ones((3,3), dtype=np.int32)
print(a1_2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [31]:
a0_2=np.zeros((4,4))
print(a0_2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
ad_2=np.eye(4)
print(ad_2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
aru_2=np.random.rand(4,5)
print(aru_2)

[[0.65596993 0.00856246 0.86291666 0.75846242 0.40867792]
 [0.39230618 0.95565384 0.62677467 0.65908546 0.30344618]
 [0.2054227  0.5413404  0.18596063 0.95098344 0.79038336]
 [0.46923383 0.35546838 0.65367638 0.74554263 0.33638618]]


In [35]:
arn_2=np.random.randn(5,4)
print(arn_2)

[[ 0.05995058  0.99294024 -0.66478435 -0.02426814]
 [ 0.46231332  1.36238487  0.36980453 -1.60938437]
 [-1.29243356 -1.06729377 -0.40646398  0.16544086]
 [ 0.05145931 -0.80743713 -0.52561915 -1.38565105]
 [ 0.07718626  0.27700251 -0.84566655  2.24595107]]


In [36]:
arr=np.random.random((3,4))
print(arr)

[[0.53380435 0.28501537 0.5931803  0.42420424]
 [0.72322805 0.06317395 0.79102904 0.64272   ]
 [0.67769382 0.89274027 0.56932971 0.30851399]]


In [39]:
print(arr.ndim, arr.dtype, arr.shape)

2 float64 (3, 4)


In [41]:
ae_2=np.empty((2,3))
print(ae_2)

[[0.33779849 0.43288564 0.03030969]
 [0.27814745 0.58404801 0.70474856]]


In [42]:
aru_2

array([[0.65596993, 0.00856246, 0.86291666, 0.75846242, 0.40867792],
       [0.39230618, 0.95565384, 0.62677467, 0.65908546, 0.30344618],
       [0.2054227 , 0.5413404 , 0.18596063, 0.95098344, 0.79038336],
       [0.46923383, 0.35546838, 0.65367638, 0.74554263, 0.33638618]])

In [44]:
print(aru_2[-2][-1])

0.7903833594477048


In [46]:
# WAP to create a 2 dimensional array by taking input from user
def create_array(rows=2,cols=2):
    arr=np.empty((rows,cols))
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            print(i,' row ',j,'column')
            arr[i][j]=int(input("Enter the value"))
    print(arr)
create_array(3,2)

0  row  0 column
Enter the value23
0  row  1 column
Enter the value12
1  row  0 column
Enter the value23
1  row  1 column
Enter the value45
2  row  0 column
Enter the value65
2  row  1 column
Enter the value3
[[23. 12.]
 [23. 45.]
 [65.  3.]]


In [47]:
print(aru_2)

[[0.65596993 0.00856246 0.86291666 0.75846242 0.40867792]
 [0.39230618 0.95565384 0.62677467 0.5677777  0.30344618]
 [0.2054227  0.5413404  0.18596063 0.95098344 0.79038336]
 [0.46923383 0.35546838 0.65367638 0.74554263 0.33638618]]


In [48]:
aru_2[1,3]

0.5677777

In [50]:
aru_2[1:4:2, 2:5:2]

array([[0.62677467, 0.30344618],
       [0.65367638, 0.33638618]])

In [52]:
aru_2

array([[0.65596993, 0.00856246, 0.86291666, 0.75846242, 0.40867792],
       [0.39230618, 0.95565384, 0.62677467, 0.5677777 , 0.30344618],
       [0.2054227 , 0.5413404 , 0.18596063, 0.95098344, 0.79038336],
       [0.46923383, 0.35546838, 0.65367638, 0.74554263, 0.33638618]])

In [53]:
aru_2[1:3,2:4]=0 #Broadcasting
print(aru_2)

[[0.65596993 0.00856246 0.86291666 0.75846242 0.40867792]
 [0.39230618 0.95565384 0.         0.         0.30344618]
 [0.2054227  0.5413404  0.         0.         0.79038336]
 [0.46923383 0.35546838 0.65367638 0.74554263 0.33638618]]


In [56]:
print(arr, arr.shape)
# reshape the total number of elements should be same

[[0.53380435 0.28501537 0.5931803  0.42420424]
 [0.72322805 0.06317395 0.79102904 0.64272   ]
 [0.67769382 0.89274027 0.56932971 0.30851399]] (3, 4)


In [58]:
arr.reshape((6,2))

array([[0.53380435, 0.28501537],
       [0.5931803 , 0.42420424],
       [0.72322805, 0.06317395],
       [0.79102904, 0.64272   ],
       [0.67769382, 0.89274027],
       [0.56932971, 0.30851399]])

In [61]:
#resize will change shape as well as number of elements
print(arr)
np.resize(arr,(4,4))

[[0.53380435 0.28501537 0.5931803  0.42420424]
 [0.72322805 0.06317395 0.79102904 0.64272   ]
 [0.67769382 0.89274027 0.56932971 0.30851399]]


array([[0.53380435, 0.28501537, 0.5931803 , 0.42420424],
       [0.72322805, 0.06317395, 0.79102904, 0.64272   ],
       [0.67769382, 0.89274027, 0.56932971, 0.30851399],
       [0.53380435, 0.28501537, 0.5931803 , 0.42420424]])

In [62]:
arr.reshape((-1,1))

array([[0.53380435],
       [0.28501537],
       [0.5931803 ],
       [0.42420424],
       [0.72322805],
       [0.06317395],
       [0.79102904],
       [0.64272   ],
       [0.67769382],
       [0.89274027],
       [0.56932971],
       [0.30851399]])

In [63]:
for i in arr:
    print(i)

[0.53380435 0.28501537 0.5931803  0.42420424]
[0.72322805 0.06317395 0.79102904 0.64272   ]
[0.67769382 0.89274027 0.56932971 0.30851399]


In [22]:
import numpy as np
arr_r=np.array(((1,2),(3,4),(4,5)))
arr_n=np.array(((4,),(5,),(6,)))
arr_1=np.array([1,2])
'''print(arr_r,"\n",arr_n,"\n",arr_1)
# arithmetic operation
print(arr_r+arr_n)
print(arr_r+arr_1)
print(arr_r-arr_n)
print(arr_r*arr_1)
print(arr_r//arr_1)
print(arr_r/arr_1)'''
print(arr_r%arr_1)

[[0 0]
 [0 0]
 [0 1]]


In [23]:
(1,2)==(1,2)

True

In [28]:
#WAP in python which will take 3 arguments, first 2 arrguments are arrays and 3rd 
#argument is operation we want to perform on array. Check the broadcasting if 
#operation is feasible or not then apply the operation and return the result

def operationonarrays(a1=np.array([1,1]),a2=np.array([1,1]),op='+'):
    s_a1=a1.shape
    s_a2=a2.shape
    if s_a1==s_a2:
        return a1+a2
    elif len(s_a1)==len(s_a2) and s_a1[0]==s_a2[0]:
        return a1+a2
    elif len(s_a1)>len(s_a2) and s_a1[1]==s_a2[0]:
        return a1+a2
    elif len(s_a1)<len(s_a2) and s_a1[0]==s_a2[1]:
        return a1+a2
    else:
        return "OPeration is not valid"
print(arr_r,"\n",arr_n,"\n",arr_1)
#operationonarrays(arr_r,arr_n)
#operationonarrays(arr_r,arr_1)
operationonarrays(arr_1,arr_r)      

[[1 2]
 [3 4]
 [4 5]] 
 [[4]
 [5]
 [6]] 
 [1 2]


array([[2, 4],
       [4, 6],
       [5, 7]])

In [29]:
print(arr_r.shape, arr_n.shape)

(3, 2) (3, 1)


In [34]:
arr_2=np.array(((2,3),(3,3)))
np.dot(arr_r,arr_2)
print(arr_r@arr_2)

[[ 8  9]
 [18 21]
 [23 27]]


In [39]:
print(arr_r)
print(np.min(arr_r))
print(np.min(arr_r,axis=1)) # row wise
print(np.min(arr_r,axis=0))  # column wise
print(np.max(arr_r))
print(np.max(arr_r,axis=1)) # row wise
print(np.max(arr_r,axis=0))  # column wise

[[1 2]
 [3 4]
 [4 5]]
1
[1 3 4]
[1 2]
5
[2 4 5]
[4 5]


In [43]:
print(np.argmin(arr_r), np.argmax(arr_r))
print(np.argmin(arr_r, axis=0), np.argmin(arr_r, axis=1))

0 5
[0 0] [0 0 0]


In [78]:
# WAP to generate an array of dimension 3,5. Generate array by taking 
#random integer values from the user, then try to sort the array

a_int=np.zeros((3,5),dtype=np.int32)
for i in range(a_int.shape[0]):
    for j in range(a_int.shape[1]):
        a_int[i,j]=np.random.randint(1,100)
print(a_int)

[[62 30 54 55 27]
 [64  9  1 19  7]
 [ 9 18 95 55 90]]


In [79]:
a_int_r=a_int.reshape(-1,1)
a_1=a_int_r[:,0]
l1=[]
print(a_1, np.argmin(a_1))
for i in range(a_int.shape[0]):
    for j in range(a_int.shape[1]):
        #print(np.min(a_1))
        l1.append(np.min(a_1))
        a_1[np.argmin(a_1)]=999


[62 30 54 55 27 64  9  1 19  7  9 18 95 55 90] 7


In [80]:
print(l1)

[1, 7, 9, 9, 18, 19, 27, 30, 54, 55, 55, 62, 64, 90, 95]


In [81]:
np.sum(a_int, axis=1)

array([4995, 4995, 4995])

In [82]:
np.mean(a_int,axis=1)

array([999., 999., 999.])

In [83]:
np.median(a_int, axis=0)

array([999., 999., 999., 999., 999.])

In [84]:
np.std(a_1)

0.0

In [85]:
np.var(a_1)

0.0

In [86]:
np.sqrt(arr_r)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.        , 2.23606798]])

In [87]:
np.exp(arr_r)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [ 54.59815003, 148.4131591 ]])

In [88]:
np.log(arr_r)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.38629436, 1.60943791]])

In [4]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack([a1,a2]))
print(np.hstack([a1,a2]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [6]:
a2_1=np.array([[1,2],[3,4]])
a2_2=np.array([[4,5],[6,7]])
print(np.hstack([a2_1,a2_2]))
print(np.vstack([a2_1, a2_2]))

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [14]:
#WAP in python to find out the commin elements in 2 different array
a3=np.arange(2,7)
print(a3)
a4=np.arange(0,5)
print(a4)
#inter,a3_indices,a4_indices=np.intersect1d(a3,a4, return_indices=True)
#print(inter,a3_indices,a4_indices)
print(np.setdiff1d(a3,a4))
# Elements which are present in 1st array but not in second
print(np.union1d(a3,a4))

[2 3 4 5 6]
[0 1 2 3 4]
[5 6]
[0 1 2 3 4 5 6]


In [28]:
# W A P in python to sort your array
a6=np.array([34,23,1,36,78,45,67,89,99,3,57,1,3,23])
sr,index,inverse=np.unique(a6, return_index=True,return_inverse=True)
"""print(sr,"\n", inverse)
for i in inverse:
    print(sr[i],end=" ")"""
a7=np.array([[4,3,89,56],[56,23,45,1]])
print(np.unique(a7,axis=1))

[[ 3  4 56 89]
 [23 56  1 45]]


In [29]:
#conditional Selection
a_int=np.zeros((3,5),dtype=np.int32)
for i in range(a_int.shape[0]):
    for j in range(a_int.shape[1]):
        a_int[i,j]=np.random.randint(1,100)
print(a_int)

[[44 52 81 56 40]
 [88 74 55 91 50]
 [97 66 80 72 31]]


In [37]:
a_int[(a_int>50) | (a_int<70)]

array([44, 52, 81, 56, 40, 88, 74, 55, 91, 50, 97, 66, 80, 72, 31])

In [40]:
(a_int>50)

array([[False,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False]])