In [1]:
print([1,2,3]+[4,5,6])

[1, 2, 3, 4, 5, 6]


In [2]:
print([1,2,3]*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [10]:
import numpy as np
#Creating array from list
a1=np.array([1,2,3])       # 1 dimensional
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])  # 2 dimensional
print(a1,"\n",a2)
print(a1.shape, a2.shape)
#print([1,2,3])
#Elements of array is seperated by space and elements of list seperated by comma

[1 2 3] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3,) (3, 3)


In [9]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]]])          #3 dimensional
print(a3, a3.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] (2, 3, 3)


In [11]:
print(a1*3)

[3 6 9]


In [27]:
# Different methods to generate array
# One dimensional method
a4=np.arange(50)
print(a4)
a5=np.linspace(1,10)
print(a5.shape)
a6=np.ones(4)
print(a6)
a7=np.zeros(5)
print(a7)
a8=np.random.randint(1,100,7)
print(a8)
a9=np.random.rand(5)    #uniform distribution  
print(a9)
a10=np.random.randn(6)  #normal Distribution
print(a10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
(50,)
[1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[23 38 73 32 92 85 31]
[0.03302869 0.85851472 0.03819489 0.1469299  0.97686839]
[ 0.33779849 -0.43288564  0.03030969 -0.27814745  0.58404801  0.70474856]


In [30]:
a1_2=np.ones((3,3), dtype=np.int32)
print(a1_2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [31]:
a0_2=np.zeros((4,4))
print(a0_2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
ad_2=np.eye(4)
print(ad_2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
aru_2=np.random.rand(4,5)
print(aru_2)

[[0.65596993 0.00856246 0.86291666 0.75846242 0.40867792]
 [0.39230618 0.95565384 0.62677467 0.65908546 0.30344618]
 [0.2054227  0.5413404  0.18596063 0.95098344 0.79038336]
 [0.46923383 0.35546838 0.65367638 0.74554263 0.33638618]]


In [35]:
arn_2=np.random.randn(5,4)
print(arn_2)

[[ 0.05995058  0.99294024 -0.66478435 -0.02426814]
 [ 0.46231332  1.36238487  0.36980453 -1.60938437]
 [-1.29243356 -1.06729377 -0.40646398  0.16544086]
 [ 0.05145931 -0.80743713 -0.52561915 -1.38565105]
 [ 0.07718626  0.27700251 -0.84566655  2.24595107]]


In [36]:
arr=np.random.random((3,4))
print(arr)

[[0.53380435 0.28501537 0.5931803  0.42420424]
 [0.72322805 0.06317395 0.79102904 0.64272   ]
 [0.67769382 0.89274027 0.56932971 0.30851399]]


In [39]:
print(arr.ndim, arr.dtype, arr.shape)

2 float64 (3, 4)


In [41]:
ae_2=np.empty((2,3))
print(ae_2)

[[0.33779849 0.43288564 0.03030969]
 [0.27814745 0.58404801 0.70474856]]


In [42]:
aru_2

array([[0.65596993, 0.00856246, 0.86291666, 0.75846242, 0.40867792],
       [0.39230618, 0.95565384, 0.62677467, 0.65908546, 0.30344618],
       [0.2054227 , 0.5413404 , 0.18596063, 0.95098344, 0.79038336],
       [0.46923383, 0.35546838, 0.65367638, 0.74554263, 0.33638618]])

In [44]:
print(aru_2[-2][-1])

0.7903833594477048


In [46]:
# WAP to create a 2 dimensional array by taking input from user
def create_array(rows=2,cols=2):
    arr=np.empty((rows,cols))
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            print(i,' row ',j,'column')
            arr[i][j]=int(input("Enter the value"))
    print(arr)
create_array(3,2)

0  row  0 column
Enter the value23
0  row  1 column
Enter the value12
1  row  0 column
Enter the value23
1  row  1 column
Enter the value45
2  row  0 column
Enter the value65
2  row  1 column
Enter the value3
[[23. 12.]
 [23. 45.]
 [65.  3.]]


In [47]:
print(aru_2)

[[0.65596993 0.00856246 0.86291666 0.75846242 0.40867792]
 [0.39230618 0.95565384 0.62677467 0.5677777  0.30344618]
 [0.2054227  0.5413404  0.18596063 0.95098344 0.79038336]
 [0.46923383 0.35546838 0.65367638 0.74554263 0.33638618]]


In [48]:
aru_2[1,3]

0.5677777

In [50]:
aru_2[1:4:2, 2:5:2]

array([[0.62677467, 0.30344618],
       [0.65367638, 0.33638618]])

In [52]:
aru_2

array([[0.65596993, 0.00856246, 0.86291666, 0.75846242, 0.40867792],
       [0.39230618, 0.95565384, 0.62677467, 0.5677777 , 0.30344618],
       [0.2054227 , 0.5413404 , 0.18596063, 0.95098344, 0.79038336],
       [0.46923383, 0.35546838, 0.65367638, 0.74554263, 0.33638618]])

In [53]:
aru_2[1:3,2:4]=0 #Broadcasting
print(aru_2)

[[0.65596993 0.00856246 0.86291666 0.75846242 0.40867792]
 [0.39230618 0.95565384 0.         0.         0.30344618]
 [0.2054227  0.5413404  0.         0.         0.79038336]
 [0.46923383 0.35546838 0.65367638 0.74554263 0.33638618]]
